#!/bin/bash

scp manage.py eraclito:/opt/houseremote
scp automation/management/commands/daemons.py eraclito:/opt/houseremote/automation/management/commands
scp automation/management/commands/initdata.py eraclito:/opt/houseremote/automation/management/commands
scp automation/static/automation/css/style.css eraclito:/opt/houseremote/static/automation/css
scp automation/static/automation/js/all.js eraclito:/opt/houseremote/static/automation/js
scp automation/static/automation/js/main.js eraclito:/opt/houseremote/static/automation/js
scp automation/static/automation/images/favicon.ico eraclito:/opt/houseremote/static/automation/images
scp automation/templates/registration/login.html eraclito:/opt/houseremote/automation/templates/registration
scp automation/templates/automation/index.html eraclito:/opt/houseremote/automation/templates/automation
scp automation/logger.py eraclito:/opt/houseremote/automation
scp automation/admin.py eraclito:/opt/houseremote/automation
scp automation/api.py eraclito:/opt/houseremote/automation
scp automation/apps.py eraclito:/opt/houseremote/automation
scp automation/gpio.py eraclito:/opt/houseremote/automation
scp automation/models.py eraclito:/opt/houseremote/automation
scp automation/redis.py eraclito:/opt/houseremote/automation
scp automation/serializers.py eraclito:/opt/houseremote/automation
scp automation/urls.py eraclito:/opt/houseremote/automation