#!/bin/bash

scp manage.py raspberry2:/opt/houseremote
scp logger.py raspberry2:/opt/houseremote
scp automation/management/commands/daemons.py raspberry2:/opt/houseremote/automation/management/commands
scp automation/management/commands/initdata.py raspberry2:/opt/houseremote/automation/management/commands
scp automation/static/automation/css/style.css raspberry2:/opt/houseremote/static/automation/css
scp automation/static/automation/js/all.js raspberry2:/opt/houseremote/static/automation/js
scp automation/static/automation/js/main.js raspberry2:/opt/houseremote/static/automation/js
scp automation/static/automation/images/favicon.ico raspberry2:/opt/houseremote/static/automation/images
scp automation/templates/registration/login.html raspberry2:/opt/houseremote/automation/templates/registration
scp automation/templates/automation/index.html raspberry2:/opt/houseremote/automation/templates/automation
scp automation/admin.py raspberry2:/opt/houseremote/automation
scp automation/api.py raspberry2:/opt/houseremote/automation
scp automation/apps.py raspberry2:/opt/houseremote/automation
scp automation/models.py raspberry2:/opt/houseremote/automation
scp automation/models.py raspberry2:/opt/houseremote/automation
scp automation/serializers.py raspberry2:/opt/houseremote/automation
scp automation/urls.py raspberry2:/opt/houseremote/automation