#!/bin/bash

scp manage.py heraclito:/opt/houseremote
scp automation/management/commands/daemons.py heraclito:/opt/houseremote/automation/management/commands
scp automation/management/commands/initdata.py heraclito:/opt/houseremote/automation/management/commands
scp automation/static/automation/css/style.css heraclito:/opt/houseremote/static/automation/css
scp automation/static/automation/js/all.js heraclito:/opt/houseremote/static/automation/js
scp automation/static/automation/js/main.js heraclito:/opt/houseremote/static/automation/js
scp automation/static/automation/images/favicon.ico heraclito:/opt/houseremote/static/automation/images
scp automation/templates/registration/login.html heraclito:/opt/houseremote/automation/templates/registration
scp automation/templates/automation/index.html heraclito:/opt/houseremote/automation/templates/automation
scp automation/logger.py heraclito:/opt/houseremote/automation
scp automation/admin.py heraclito:/opt/houseremote/automation
scp automation/api.py heraclito:/opt/houseremote/automation
scp automation/apps.py heraclito:/opt/houseremote/automation
scp automation/gpio.py heraclito:/opt/houseremote/automation
scp automation/models.py heraclito:/opt/houseremote/automation
scp automation/redis.py heraclito:/opt/houseremote/automation
scp automation/serializers.py heraclito:/opt/houseremote/automation
scp automation/urls.py heraclito:/opt/houseremote/automation
scp automation/notify.py heraclito:/opt/houseremote/automation
