#!/bin/bash

scp db_maintenance.py raspberry1:/home/pi/Documents/raspberry
scp indicator.py raspberry1:/home/pi/Documents/raspberry
scp light_sensor.py raspberry1:/home/pi/Documents/raspberry
scp logger.py raspberry1:/home/pi/Documents/raspberry
scp manage.py raspberry1:/home/pi/Documents/raspberry
scp notify.py raspberry1:/home/pi/Documents/raspberry
scp pir_sensor.py raspberry1:/home/pi/Documents/raspberry
scp test_lights.py raspberry1:/home/pi/Documents/raspberry
scp test_listen.py raspberry1:/home/pi/Documents/raspberry
scp test_send.py raspberry1:/home/pi/Documents/raspberry

scp automation/admin.py raspberry1:/home/pi/Documents/raspberry/automation
scp automation/api.py raspberry1:/home/pi/Documents/raspberry/automation
scp automation/apps.py raspberry1:/home/pi/Documents/raspberry/automation
scp automation/models.py raspberry1:/home/pi/Documents/raspberry/automation
scp automation/serializers.py raspberry1:/home/pi/Documents/raspberry/automation
scp automation/urls.py raspberry1:/home/pi/Documents/raspberry/automation

scp automation/static/automation/all.js raspberry1:/home/pi/Documents/raspberry/automation/static/automation
scp automation/static/automation/main.js raspberry1:/home/pi/Documents/raspberry/automation/static/automation
scp -r automation/static/automation/css/ raspberry1:/home/pi/Documents/raspberry/automation/static/automation
scp -r automation/static/automation/images/ raspberry1:/home/pi/Documents/raspberry/automation/static/automation

scp automation/templates/registration/login.html raspberry1:/home/pi/Documents/raspberry/automation/templates/registration
scp automation/templates/automation/index.html raspberry1:/home/pi/Documents/raspberry/automation/templates/automation
