# Generated by Django 2.2 on 2020-11-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armed', models.BooleanField(default=False)),
                ('fired', models.BooleanField(default=False)),
                ('eventDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='event date')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Group')),
            ],
        ),
        migrations.CreateModel(
            name='GPIOInputType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='GPIOOutputType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationClient',
            fields=[
                ('client_id', models.CharField(max_length=80)),
                ('registration_id', models.TextField()),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='registration_date')),
                ('registration_update', models.DateTimeField(auto_now=True, verbose_name='registration_update')),
                ('device_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'get_latest_by': 'registration_update',
            },
        ),
        migrations.CreateModel(
            name='PioneerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='PioneerDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.DeviceGroup')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='automation.PioneerType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LightState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('brightness', models.IntegerField()),
                ('isDark', models.BooleanField()),
            ],
            options={
                'get_latest_by': 'date',
                'unique_together': {('date', 'isDark')},
            },
        ),
        migrations.CreateModel(
            name='GPIOOutputDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('pinNumber', models.IntegerField(verbose_name='pin number')),
                ('address', models.CharField(default='127.0.0.1', editable=False, max_length=50)),
                ('autoEnabled', models.BooleanField(default=False)),
                ('simulationEnabled', models.BooleanField(default=False)),
                ('clapEnabled', models.BooleanField(default=False)),
                ('longTimeStart', models.TimeField(blank=True, null=True)),
                ('longTimeEnd', models.TimeField(blank=True, null=True)),
                ('longTimeDuration', models.IntegerField(default=3600)),
                ('shortTimeDuration', models.IntegerField(default=30)),
                ('status', models.BooleanField(default=False, editable=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.DeviceGroup')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='automation.GPIOOutputType')),
            ],
            options={
                'abstract': False,
                'unique_together': {('pinNumber', 'address')},
            },
        ),
        migrations.CreateModel(
            name='PioneerDeviceAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfUse', models.DateTimeField(auto_now_add=True, verbose_name='date of use')),
                ('status', models.BooleanField()),
                ('isAutomatic', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.PioneerDevice')),
            ],
            options={
                'abstract': False,
                'unique_together': {('device', 'dateOfUse')},
            },
        ),
        migrations.CreateModel(
            name='GPIOInputDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('pinNumber', models.IntegerField(verbose_name='pin number')),
                ('address', models.CharField(default='127.0.0.1', editable=False, max_length=50)),
                ('threshold', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.DeviceGroup')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='automation.GPIOInputType')),
            ],
            options={
                'abstract': False,
                'unique_together': {('pinNumber', 'address')},
            },
        ),
        migrations.CreateModel(
            name='GPIODeviceAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfUse', models.DateTimeField(auto_now_add=True, verbose_name='date of use')),
                ('status', models.BooleanField()),
                ('isAutomatic', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.GPIOOutputDevice')),
            ],
            options={
                'abstract': False,
                'unique_together': {('device', 'dateOfUse')},
            },
        ),
    ]
