# Generated by Django 3.2.4 on 2022-08-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionhistory',
            name='who',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
