# Generated by Django 3.2.4 on 2022-09-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_actionhistory_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirsensor',
            name='camera',
            field=models.BooleanField(default=False),
        ),
    ]
