# Generated by Django 3.2.4 on 2023-01-29 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_pirsensor_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('priority', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='automation.action')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
